mode: auto

pjax:
  enable: true

favicon: https://cdn.fwder.cn/images/favicon.ico

head:
  js:
    async:
      iconfont: //at.alicdn.com/t/font_3297175_2ml40aoltmp.js

avatar:
  url: https://cdn.fwder.cn/images/header.jpg
  status:
    enable: true

bg_image:
  enable: false

reward:
  enable: false

wordcloud:
  enable: true

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

banner:
  enable: true
  title: 旋转吧！雪月花
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .post-content img

mourn:
  enable: false

notice:
  enable: true
  content: "本站是一个可爱的番剧资源整合网站，快来这里寻找你想要的番剧吧！&nbsp;由 AnimeCDN 提供服务。"

comment:
  enable: true
  tips:
    - 如果您有任何关于番剧内容的相关讨论，欢迎在下方评论区留言。
  candidates:
    - waline

waline:
  enable: true
  dark: auto
  serverURL: comment.blog.fwder.cn
  emoji: [
    'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/weibo',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/alus',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/qq',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tieba',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tw-emoji'
  ]
  visitor: true
  comment: true

engine_search:
  enable: false

local_search:
  enable: true
  src: /js/search/local-search.js

codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

github_issues:
  enable: false

github_discussions:
  enable: false

footer:
  since: 2022
  icon: 
    url: https://github.com/AnimeCDN/AnimeCDN
    title: 本站由 AnimeCDN 提供服务~
  beian:
    enable: false
  support:
    enable: false
  custom_text:
  powered:
    enable: true
  live_time:
    enable: false
    prefix: maware在站长的折腾下勉强运行了
    suffix: (●'◡'●)
    start_time: "2022-04-03T00:00:00"

post_edit:
  enable: false

albums:
  enable: false

girls:
  enable: false

pages:
  - name: 其他页面
    url: /pages/
    icon: icon-pages
    color: '#FFD306'
  - name: 节点列表
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue

menu:
  custom:
    title: 留言板
    path: /about/#comment
    icon: icon-clipboard-line

cursor:
  enable: true

baidu_push: true

wordcount:
  enable: true
  count: true
  time: true

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn/?c=a

katex:
  copy_tex: true
  global: false

social:
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: GitHub
    link: https://github.com/AnimeCDN/AnimeCDN
    icon: icon-github-line
    color: "#6e5494"
  - name: Travelling
    link: https://travellings.link
    icon: icon-train-line
    color: black